### ISSUE TITLE
The firefox extension just... doesn't work

### ISSUE THREAD

**Issue by hujiba** [pozz94/BandcampRemainingCopiesExtension#1]
I don't know why or anything. I installed it and it didn't change anything on the bandcamp site

**Comment by pozz94** [comment]
If you look on the page of an album, if it has a physical release, you will see availability info just below the title beneath the artist name.

**Comment by hujiba** [comment]
Strange, it works now. It absolutely did not have that section yesterday but it does not. Thanks!
